name: Super-Linter

on:
  push:
    branches:
      - main

jobs:
  super-linter:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
